USE [master]
GO

/****** Object:  Database [HomeLibrary]    Script Date: 12-Jan-17 21:30:19 ******/
CREATE DATABASE [HomeLibrary]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HomeLibrary', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLSERVER\MSSQL\DATA\HomeLibrary.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'HomeLibrary_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLSERVER\MSSQL\DATA\HomeLibrary_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [HomeLibrary] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HomeLibrary].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HomeLibrary] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HomeLibrary] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HomeLibrary] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HomeLibrary] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HomeLibrary] SET ARITHABORT OFF 
GO

ALTER DATABASE [HomeLibrary] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HomeLibrary] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [HomeLibrary] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HomeLibrary] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HomeLibrary] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HomeLibrary] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HomeLibrary] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HomeLibrary] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HomeLibrary] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HomeLibrary] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HomeLibrary] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HomeLibrary] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HomeLibrary] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HomeLibrary] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HomeLibrary] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HomeLibrary] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HomeLibrary] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HomeLibrary] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HomeLibrary] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [HomeLibrary] SET  MULTI_USER 
GO

ALTER DATABASE [HomeLibrary] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HomeLibrary] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HomeLibrary] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HomeLibrary] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [HomeLibrary] SET  READ_WRITE 
GO

